version: '3'

services:
  frontend:
    image: ghcr.io/nevah5/manametrics-frontend:latest
    ports:
      - "8007:80"
    restart: always
  backend:
    image: ghcr.io/nevah5/manametrics-backend:latest
    environment:
      GLOBAL_BASEPATH: "/api"
    ports:
      - "8008:3000"
    restart: always
