version: '3'

services:
  frontend:
    image: ghcr.io/nevah5/mtg-stats-frontend:latest
    ports:
      - "8007:80"
    restart: always
  backend:
    image: ghcr.io/nevah5/mtg-stats-backend:latest
    env:
      GLOBAL_BASEPATH: "/api"
    ports:
      - "8008:3000"
    restart: always
