on:
  push:
    branches:
      - main
  workflow_dispatch:

name: CD Pipeline

jobs:
  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Setup Wireguard VPN
        run: |
          echo "Setting up Wireguard VPN..."
          sudo apt update
          sudo apt install wireguard
          echo "Installed Wireguard VPN!"
      - name: Configure Wireguard VPN
        run: |
          echo "Configuring Wireguard VPN..."
          echo -n "${{ secrets.WIREGUARD_VPN_CONFIG }}" | base64 --decode > wg0.conf
          echo "Connecting VPN Tunnel..."
          sudo wg-quick up ./wg0.conf
          echo "Configured Wireguard VPN!"
      - name: Login to Portainer
        run: |
          echo "Logging in to Portainer..."
          RESPONSE=$(curl -s -X POST https://portainer.geeler.net/api/auth \
            -H "Content-Type: application/json" \
            -d '{"username": "${{ secrets.PORTAINER_USER }}", "password": "${{ secrets.PORTAINER_PASSWORD }}"}')
          JWT=$(echo $RESPONSE | jq -r '.jwt')
          echo "JWT=$JWT" >> $GITHUB_ENV
          echo "Logged in successfully."
