on:
  push:

name: CI Pipeline

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Build
        run: |
          echo "Building Docker image..."
          cd frontend
          docker build -t mtg-stats-frontend:latest .
          echo "Docker image built!"
      - name: Login to ghcr.io
        if: github.ref_name == 'develop' || github.ref_name == 'main'
        run: |
          echo "Logging in to ghcr.io..."
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "Logged in successfully."
      - name: Push Docker image to ghcr.io (develop)
        if: github.ref_name == 'develop'
        run: |
          echo "Pushing Docker image to ghcr.io..."
          docker tag mtg-stats-frontend:latest ghcr.io/nevah5/mtg-stats-frontend:develop
          docker push ghcr.io/nevah5/mtg-stats-frontend:develop
          echo "Docker image pushed!"
      - name: Push Docker image to ghcr.io (main)
        if: github.ref_name == 'main'
        run: |
          echo "Pushing Docker image to ghcr.io..."
          docker tag mtg-stats-frontend:latest ghcr.io/nevah5/mtg-stats-frontend:latest
          docker push ghcr.io/nevah5/mtg-stats-frontend:latest
          echo "Docker image pushed!"
